initial
p2p-org/ether-bench pull request #1
Opened 2023-06-12 19:17 UTC by a10zn8

2023-06-13 08:00 UTC, KirillPamPam commented on run.go
> +		return
Maybe also add `fmt.Println(err)`?

2023-06-13 09:36 UTC, KirillPamPam commented on run.go
> +	}
Add `return` to stop executing?

2023-06-13 09:37 UTC, KirillPamPam commented on run.go
> +	}
Also `return`?

2023-06-13 10:30 UTC, KirillPamPam commented on run.go
> +			cancel()
I'm not sure, but is it better to use `defer cancel()` before all this code?

2023-06-13 13:35 UTC, a10zn8 commented on run.go
> +		return
flags.Parse also prints error

2023-06-13 13:40 UTC, a10zn8 commented on run.go
> +			cancel()
defer executes at the end of function scope, but here i need to close resources on each iteration of loop

2023-06-13 13:42 UTC, KirillPamPam approved these changes

2023-06-14 05:29 UTC, scripter-v requested changes

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +			RandSrc: randSrc,
`rand.Source` isn't thread safe so it's better to make it inside goroutine.

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +				queries <- q.GetBody()
We can hang here, so this will lead goroutines leak. The best solution is to add another select here.

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +		for {
Let's add `defer close(queries)` before loop

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +		for {
Let's add `defer close(stateChannel)` before loop

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +func NewEthSpamTargeter(host string, queryParams map[string]int64, parentHost string, ctx context.Context) vegeta.Targeter {
context is usually put first

2023-06-14 05:29 UTC, scripter-v commented on run.go
> +			}
should be `return` in `ctx.Done` case

2023-06-14 13:07 UTC, scripter-v approved these changes

2023-06-15 16:29 UTC, merged